<?php
$_INI_ENVIRONMENT =  '__$INI_ENVIRONMENT__';
$_INI_SYSTEM_PATH =  '__$INI_SYSTEM_PATH__';
$_INI_APPLICATION_PATH =  '__$INI_APPLICATION_PATH__';
$_INI_DEVELOPER_ID = '__$INI_DEVELOPER_ID__';

date_default_timezone_set('__$INI_DEFAULT_TIMEZONE__');
